#!/bin/bash
vol=$(MPD_HOST=127.0.0.1 mpc status | cut -d' ' -f2 | sed -e 's/%/ /g')
if [ $vol -gt "75" ]
then
    icon=$(echo "   " )
elif [ $vol -gt "35" ] 
then
    icon=$(echo "   " )
else
    icon=$(echo "   ")
fi
echo " $icon "
